### PR TITLE
Laboratory work #3, Garanina Maria - 19FPL1

### PR DESCRIPTION
**Pull request by mgaranina**

### CODE REVIEW

**Comment by mgaranina** [comment]
in top_n_grams function we are supposed to use n_gram_frequencies (as given in tests) or n_gram_log_probabilities (as said in laboratory work description) ?

**Comment by dmitry-uraev** [comment]
> in top_n_grams function we are supposed to use n_gram_frequencies (as given in tests) or n_gram_log_probabilities (as said in laboratory work description) ?

it does not matter, because using either probabilities or frequencies gives you top n_grams

**Review by dmitry-uraev — COMMENTED** [review]
Good. Keep going on

**Comment by dmitry-uraev** [comment]
Nice one! Done

**Pull request closed without merging**
